In [1]:
from nerfstudio.model_components.nesf_components import *
import torch

/data/vision/polina/projects/wmh/dhollidt/conda/envs/nerfstudio2/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /data/vision/polina/projects/wmh/dhollidt/conda/envs/nerfstudio2/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")


In [2]:
mc = MaskerConfig(
    mode="patch_fp",
    mask_ratio=0.5,
    num_patches=400
)


num_points = 1000
num_features = 48

masker: Masker = mc.setup(output_size=num_features)


In [3]:
# generate data


points = torch.rand(1, num_points, 3)
outs = torch.arange(num_points).repeat(num_features, 1).transpose(0, 1).unsqueeze(0).float()

batch = {"points_xyz": points}

print("points_xyz: ", points.shape, "outs: ", outs.shape)
print(outs)

points_xyz:  torch.Size([1, 1000, 3]) outs:  torch.Size([1, 1000, 48])
tensor([[[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
         [  1.,   1.,   1.,  ...,   1.,   1.,   1.],
         [  2.,   2.,   2.,  ...,   2.,   2.,   2.],
         ...,
         [997., 997., 997.,  ..., 997., 997., 997.],
         [998., 998., 998.,  ..., 998., 998., 998.],
         [999., 999., 999.,  ..., 999., 999., 999.]]])


In [4]:
outs, mask, ids_restore, batch = masker.mask(outs, batch)

print(outs, outs.shape)
print(outs.unique())

FPS took 0.057776451110839844
tensor([[[649., 649., 649.,  ..., 649., 649., 649.],
         [261., 261., 261.,  ..., 261., 261., 261.],
         [783., 783., 783.,  ..., 783., 783., 783.],
         ...,
         [716., 716., 716.,  ..., 716., 716., 716.],
         [250., 250., 250.,  ..., 250., 250., 250.],
         [468., 468., 468.,  ..., 468., 468., 468.]]]) torch.Size([1, 500, 48])
tensor([  0.,   1.,   2.,   4.,   6.,   8.,   9.,  10.,  12.,  16.,  20.,  22.,
         23.,  24.,  25.,  27.,  28.,  29.,  31.,  32.,  34.,  36.,  37.,  39.,
         40.,  41.,  42.,  44.,  45.,  47.,  51.,  52.,  54.,  55.,  58.,  59.,
         63.,  64.,  68.,  69.,  71.,  72.,  75.,  77.,  78.,  79.,  80.,  81.,
         84.,  85.,  90.,  91.,  92.,  97.,  98.,  99., 103., 104., 105., 106.,
        108., 109., 110., 111., 112., 113., 114., 115., 116., 118., 120., 122.,
        125., 128., 129., 133., 137., 138., 139., 140., 144., 145., 146., 147.,
        150., 153., 154., 156., 157., 159., 160., 1

In [5]:
outs, transform_batch = masker.unmask(outs, batch, ids_restore)

print(outs, outs.shape)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  ...,  1.0000e+00,
           1.0000e+00,  1.0000e+00],
         [ 2.0000e+00,  2.0000e+00,  2.0000e+00,  ...,  2.0000e+00,
           2.0000e+00,  2.0000e+00],
         ...,
         [-5.1461e-01,  3.1993e-01,  8.5091e-01,  ..., -5.6706e-02,
          -4.2983e-01,  1.5155e-01],
         [ 9.9800e+02,  9.9800e+02,  9.9800e+02,  ...,  9.9800e+02,
           9.9800e+02,  9.9800e+02],
         [ 9.4348e-01, -1.4935e-01,  4.6887e-01,  ..., -5.6706e-02,
          -4.2983e-01,  1.5155e-01]]], grad_fn=<GatherBackward0>) torch.Size([1, 1000, 48])


In [6]:
outs[0][:, 0]

tensor([ 0.0000e+00,  1.0000e+00,  2.0000e+00, -6.1112e-01,  4.0000e+00,
         1.3744e+00,  6.0000e+00, -6.0984e-01,  8.0000e+00,  9.0000e+00,
         1.0000e+01,  8.0572e-01,  1.2000e+01,  8.2530e-01, -1.0986e-01,
        -5.7067e-01,  1.6000e+01,  1.2906e+00,  2.8088e-01,  2.0664e-01,
         2.0000e+01,  1.3675e+00,  2.2000e+01,  2.3000e+01,  2.4000e+01,
         2.5000e+01,  1.3739e+00,  2.7000e+01,  2.8000e+01,  2.9000e+01,
         8.8396e-01,  3.1000e+01,  3.2000e+01,  9.9142e-01,  3.4000e+01,
         7.8628e-01,  3.6000e+01,  3.7000e+01,  1.5104e-01,  3.9000e+01,
         4.0000e+01,  4.1000e+01,  4.2000e+01,  1.2333e+00,  4.4000e+01,
         4.5000e+01,  1.3346e+00,  4.7000e+01, -4.7967e-02,  1.3743e+00,
        -6.1108e-01,  5.1000e+01,  5.2000e+01, -6.2201e-01,  5.4000e+01,
         5.5000e+01,  1.3713e+00,  1.3700e+00,  5.8000e+01,  5.9000e+01,
         6.0195e-02, -3.7641e-01,  1.3739e+00,  6.3000e+01,  6.4000e+01,
         8.1128e-01,  1.1855e+00, -5.7488e-01,  6.8